library(DESeq2)
library(DEGreport)
library(tibble)
library(ggplot2)
library(tximport)
library(readr)

#txi <- readRDS(file = "/Users/rbadgami/Desktop/data2/read_count_data/txi.RData")
### Get previous data that will feed into this
#source('~/Desktop/data2/Rscripts_2/tximport.R')
#source('~/Desktop/data2/Rscripts_2/DESeq2_initial.R')

dds <- DESeqDataSetFromTximport(txi,colData=ExpVar,design=~cultivar_isolate)

dds <- DESeqDataSetFromTximport(txi, colData=ExpVar, design= ~ cultivar + timepoint + cultivar:timepoint)
dds$cultivar_isolate=as.factor(dds$cultivar_isolate)
dds$cultivar=as.factor(dds$cultivar)
dds$timepoint=as.factor(dds$timepoint)
dds$isolate=as.factor(dds$isolate)

design(dds) <- formula(~cultivar + timepoint + cultivar:timepoint)
dds <- dds[rowSums(counts(dds)) > 1, ]

#### filter for cultivars at each timepoint ####
dds_F22  <- dds[, dds$isolate == "F22"]
dds_F22$isolate <- droplevels(dds_F22$isolate)
dds_F22$timepoint=as.factor(dds_F22$timepoint)
dds_F22_normalised_counts <- counts(dds_F22, normalized=TRUE)
#timepoint
dds_F22_1dpi <- dds_F22[, dds_F22$timepoint == "1"]
dds_F22_1dpi$timepoint <- droplevels(dds_F22_1dpi$timepoint)
dds_F22_3dpi <- dds_F22[, dds_F22$timepoint == "3"]
dds_F22_3dpi$timepoint <- droplevels(dds_F22_3dpi$timepoint)
dds_F22_7dpi <- dds_F22[, dds_F22$timepoint == "7"]
dds_F22_7dpi$timepoint <- droplevels(dds_F22_7dpi$timepoint)
dds_F22_11dpi <- dds_F22[, dds_F22$timepoint == "11"]
dds_F22_11dpi$timepoint <- droplevels(dds_F22_11dpi$timepoint)
#cultivars
dds_F22_1dpi_SAvOA <- dds_F22_1dpi[, dds_F22_1dpi$cultivar %in% c("SA", "OA")]
dds_F22_1dpi_SAvOA$cultivar <- droplevels(dds_F22_1dpi_SAvOA$cultivar)
dds_F22_1dpi_SAvOA$cultivar <- relevel( dds_F22_1dpi_SAvOA$cultivar, "OA" )
dds_F22_1dpi_SOvOA <- dds_F22_1dpi[, dds_F22_1dpi$cultivar %in% c("SO", "OA")]
dds_F22_1dpi_SOvOA$cultivar <- droplevels(dds_F22_1dpi_SOvOA$cultivar)
dds_F22_1dpi_SOvOA$cultivar <- relevel( dds_F22_1dpi_SOvOA$cultivar, "OA" )
dds_F22_1dpi_SAvSO <- dds_F22_1dpi[, dds_F22_1dpi$cultivar %in% c("SA", "SO")]
dds_F22_1dpi_SAvSO$cultivar <- droplevels(dds_F22_1dpi_SAvSO$cultivar)
dds_F22_1dpi_SAvSO$cultivar <- relevel( dds_F22_1dpi_SAvSO$cultivar, "SO" )
dds_F22_3dpi_SAvOA <- dds_F22_3dpi[, dds_F22_3dpi$cultivar %in% c("SA", "OA")]
dds_F22_3dpi_SAvOA$cultivar <- droplevels(dds_F22_3dpi_SAvOA$cultivar)
dds_F22_3dpi_SAvOA$cultivar <- relevel( dds_F22_3dpi_SAvOA$cultivar, "OA" )
dds_F22_3dpi_SOvOA <- dds_F22_3dpi[, dds_F22_3dpi$cultivar %in% c("SO", "OA")]
dds_F22_3dpi_SOvOA$cultivar <- droplevels(dds_F22_3dpi_SOvOA$cultivar)
dds_F22_3dpi_SOvOA$cultivar <- relevel( dds_F22_3dpi_SOvOA$cultivar, "OA" )
dds_F22_3dpi_SAvSO <- dds_F22_3dpi[, dds_F22_3dpi$cultivar %in% c("SA", "SO")]
dds_F22_3dpi_SAvSO$cultivar <- droplevels(dds_F22_3dpi_SAvSO$cultivar)
dds_F22_3dpi_SAvSO$cultivar <- relevel( dds_F22_3dpi_SAvSO$cultivar, "SO" )
dds_F22_7dpi_SAvOA <- dds_F22_7dpi[, dds_F22_7dpi$cultivar %in% c("SA", "OA")]
dds_F22_7dpi_SAvOA$cultivar <- droplevels(dds_F22_7dpi_SAvOA$cultivar)
dds_F22_7dpi_SAvOA$cultivar <- relevel( dds_F22_7dpi_SAvOA$cultivar, "OA" )
dds_F22_7dpi_SOvOA <- dds_F22_7dpi[, dds_F22_7dpi$cultivar %in% c("SO", "OA")]
dds_F22_7dpi_SOvOA$cultivar <- droplevels(dds_F22_7dpi_SOvOA$cultivar)
dds_F22_7dpi_SOvOA$cultivar <- relevel( dds_F22_7dpi_SOvOA$cultivar, "OA" )
dds_F22_7dpi_SAvSO <- dds_F22_7dpi[, dds_F22_7dpi$cultivar %in% c("SA", "SO")]
dds_F22_7dpi_SAvSO$cultivar <- droplevels(dds_F22_7dpi_SAvSO$cultivar)
dds_F22_7dpi_SAvSO$cultivar <- relevel( dds_F22_7dpi_SAvSO$cultivar, "SO" )
dds_F22_11dpi_SAvOA <- dds_F22_11dpi[, dds_F22_11dpi$cultivar %in% c("SA", "OA")]
dds_F22_11dpi_SAvOA$cultivar <- droplevels(dds_F22_11dpi_SAvOA$cultivar)
dds_F22_11dpi_SAvOA$cultivar <- relevel( dds_F22_11dpi_SAvOA$cultivar, "OA" )
dds_F22_11dpi_SOvOA <- dds_F22_11dpi[, dds_F22_11dpi$cultivar %in% c("SO", "OA")]
dds_F22_11dpi_SOvOA$cultivar <- droplevels(dds_F22_11dpi_SOvOA$cultivar)
dds_F22_11dpi_SOvOA$cultivar <- relevel( dds_F22_11dpi_SOvOA$cultivar, "OA" )
dds_F22_11dpi_SAvSO <- dds_F22_11dpi[, dds_F22_11dpi$cultivar %in% c("SA", "SO")]
dds_F22_11dpi_SAvSO$cultivar <- droplevels(dds_F22_11dpi_SAvSO$cultivar)
dds_F22_11dpi_SAvSO$cultivar <- relevel( dds_F22_11dpi_SAvSO$cultivar, "SO" )
#for 1314
dds_1314  <- dds[, dds$isolate == "1314"]
dds_1314$isolate <- droplevels(dds_1314$isolate)
dds_1314$timepoint=as.factor(dds_1314$timepoint)
dds_1314_normalised_counts <- counts(dds_1314, normalized=TRUE)
#timepoint
dds_1314_1dpi <- dds_1314[, dds_1314$timepoint == "1"]
dds_1314_1dpi$timepoint <- droplevels(dds_1314_1dpi$timepoint)
dds_1314_3dpi <- dds_1314[, dds_1314$timepoint == "3"]
dds_1314_3dpi$timepoint <- droplevels(dds_1314_3dpi$timepoint)
dds_1314_7dpi <- dds_1314[, dds_1314$timepoint == "7"]
dds_1314_7dpi$timepoint <- droplevels(dds_1314_7dpi$timepoint)
dds_1314_11dpi <- dds_1314[, dds_1314$timepoint == "11"]
dds_1314_11dpi$timepoint <- droplevels(dds_1314_11dpi$timepoint)
#cultivars
dds_1314_1dpi_SAvOA <- dds_1314_1dpi[, dds_1314_1dpi$cultivar %in% c("SA", "OA")]
dds_1314_1dpi_SAvOA$cultivar <- droplevels(dds_1314_1dpi_SAvOA$cultivar)
dds_1314_1dpi_SAvOA$cultivar <- relevel( dds_1314_1dpi_SAvOA$cultivar, "OA" )
dds_1314_1dpi_SOvOA <- dds_1314_1dpi[, dds_1314_1dpi$cultivar %in% c("SO", "OA")]
dds_1314_1dpi_SOvOA$cultivar <- droplevels(dds_1314_1dpi_SOvOA$cultivar)
dds_1314_1dpi_SOvOA$cultivar <- relevel( dds_1314_1dpi_SOvOA$cultivar, "OA" )
dds_1314_1dpi_SAvSO <- dds_1314_1dpi[, dds_1314_1dpi$cultivar %in% c("SA", "SO")]
dds_1314_1dpi_SAvSO$cultivar <- droplevels(dds_1314_1dpi_SAvSO$cultivar)
dds_1314_1dpi_SAvSO$cultivar <- relevel( dds_1314_1dpi_SAvSO$cultivar, "SO" )
dds_1314_3dpi_SAvOA <- dds_1314_3dpi[, dds_1314_3dpi$cultivar %in% c("SA", "OA")]
dds_1314_3dpi_SAvOA$cultivar <- droplevels(dds_1314_3dpi_SAvOA$cultivar)
dds_1314_3dpi_SAvOA$cultivar <- relevel( dds_1314_3dpi_SAvOA$cultivar, "OA" )
dds_1314_3dpi_SOvOA <- dds_1314_3dpi[, dds_1314_3dpi$cultivar %in% c("SO", "OA")]
dds_1314_3dpi_SOvOA$cultivar <- droplevels(dds_1314_3dpi_SOvOA$cultivar)
dds_1314_3dpi_SOvOA$cultivar <- relevel( dds_1314_3dpi_SOvOA$cultivar, "OA" )
dds_1314_3dpi_SAvSO <- dds_1314_3dpi[, dds_1314_3dpi$cultivar %in% c("SA", "SO")]
dds_1314_3dpi_SAvSO$cultivar <- droplevels(dds_1314_3dpi_SAvSO$cultivar)
dds_1314_3dpi_SAvSO$cultivar <- relevel( dds_1314_3dpi_SAvSO$cultivar, "SO" )
dds_1314_7dpi_SAvOA <- dds_1314_7dpi[, dds_1314_7dpi$cultivar %in% c("SA", "OA")]
dds_1314_7dpi_SAvOA$cultivar <- droplevels(dds_1314_7dpi_SAvOA$cultivar)
dds_1314_7dpi_SAvOA$cultivar <- relevel( dds_1314_7dpi_SAvOA$cultivar, "OA" )
dds_1314_7dpi_SOvOA <- dds_1314_7dpi[, dds_1314_7dpi$cultivar %in% c("SO", "OA")]
dds_1314_7dpi_SOvOA$cultivar <- droplevels(dds_1314_7dpi_SOvOA$cultivar)
dds_1314_7dpi_SOvOA$cultivar <- relevel( dds_1314_7dpi_SOvOA$cultivar, "OA" )
dds_1314_7dpi_SAvSO <- dds_1314_7dpi[, dds_1314_7dpi$cultivar %in% c("SA", "SO")]
dds_1314_7dpi_SAvSO$cultivar <- droplevels(dds_1314_7dpi_SAvSO$cultivar)
dds_1314_7dpi_SAvSO$cultivar <- relevel( dds_1314_7dpi_SAvSO$cultivar, "SO" )
dds_1314_11dpi_SAvOA <- dds_1314_11dpi[, dds_1314_11dpi$cultivar %in% c("SA", "OA")]
dds_1314_11dpi_SAvOA$cultivar <- droplevels(dds_1314_11dpi_SAvOA$cultivar)
dds_1314_11dpi_SAvOA$cultivar <- relevel( dds_1314_11dpi_SAvOA$cultivar, "OA" )
dds_1314_11dpi_SOvOA <- dds_1314_11dpi[, dds_1314_11dpi$cultivar %in% c("SO", "OA")]
dds_1314_11dpi_SOvOA$cultivar <- droplevels(dds_1314_11dpi_SOvOA$cultivar)
dds_1314_11dpi_SOvOA$cultivar <- relevel( dds_1314_11dpi_SOvOA$cultivar, "OA" )
dds_1314_11dpi_SAvSO <- dds_1314_11dpi[, dds_1314_11dpi$cultivar %in% c("SA", "SO")]
dds_1314_11dpi_SAvSO$cultivar <- droplevels(dds_1314_11dpi_SAvSO$cultivar)
dds_1314_11dpi_SAvSO$cultivar <- relevel( dds_1314_11dpi_SAvSO$cultivar, "SO" )

#### Fit generalised linear (negative binomial) model ####
design(dds_F22_1dpi_SAvOA) <- formula(~ cultivar)
dds_F22_1dpi_SAvOA <- DESeq(dds_F22_1dpi_SAvOA)
design(dds_F22_1dpi_SOvOA) <- formula(~ cultivar)
dds_F22_1dpi_SOvOA <- DESeq(dds_F22_1dpi_SOvOA)
design(dds_F22_1dpi_SAvSO) <- formula(~ cultivar)
dds_F22_1dpi_SAvSO <- DESeq(dds_F22_1dpi_SAvSO)
design(dds_F22_3dpi_SAvOA) <- formula(~ cultivar)
dds_F22_3dpi_SAvOA <- DESeq(dds_F22_3dpi_SAvOA)
design(dds_F22_3dpi_SOvOA) <- formula(~ cultivar)
dds_F22_3dpi_SOvOA <- DESeq(dds_F22_3dpi_SOvOA)
design(dds_F22_3dpi_SAvSO) <- formula(~ cultivar)
dds_F22_3dpi_SAvSO <- DESeq(dds_F22_3dpi_SAvSO)
design(dds_F22_7dpi_SAvOA) <- formula(~ cultivar)
dds_F22_7dpi_SAvOA <- DESeq(dds_F22_7dpi_SAvOA)
design(dds_F22_7dpi_SOvOA) <- formula(~ cultivar)
dds_F22_7dpi_SOvOA <- DESeq(dds_F22_7dpi_SOvOA)
design(dds_F22_7dpi_SAvSO) <- formula(~ cultivar)
dds_F22_7dpi_SAvSO <- DESeq(dds_F22_7dpi_SAvSO)
design(dds_F22_11dpi_SAvOA) <- formula(~ cultivar)
dds_F22_11dpi_SAvOA <- DESeq(dds_F22_11dpi_SAvOA)
design(dds_F22_11dpi_SOvOA) <- formula(~ cultivar)
dds_F22_11dpi_SOvOA <- DESeq(dds_F22_11dpi_SOvOA)
design(dds_F22_11dpi_SAvSO) <- formula(~ cultivar)
dds_F22_11dpi_SAvSO <- DESeq(dds_F22_11dpi_SAvSO)
#for 1314
design(dds_1314_1dpi_SAvOA) <- formula(~ cultivar)
dds_1314_1dpi_SAvOA <- DESeq(dds_1314_1dpi_SAvOA)
design(dds_1314_1dpi_SOvOA) <- formula(~ cultivar)
dds_1314_1dpi_SOvOA <- DESeq(dds_1314_1dpi_SOvOA)
design(dds_1314_1dpi_SAvSO) <- formula(~ cultivar)
dds_1314_1dpi_SAvSO <- DESeq(dds_1314_1dpi_SAvSO)
design(dds_1314_3dpi_SAvOA) <- formula(~ cultivar)
dds_1314_3dpi_SAvOA <- DESeq(dds_1314_3dpi_SAvOA)
design(dds_1314_3dpi_SOvOA) <- formula(~ cultivar)
dds_1314_3dpi_SOvOA <- DESeq(dds_1314_3dpi_SOvOA)
design(dds_1314_3dpi_SAvSO) <- formula(~ cultivar)
dds_1314_3dpi_SAvSO <- DESeq(dds_1314_3dpi_SAvSO)
design(dds_1314_7dpi_SAvOA) <- formula(~ cultivar)
dds_1314_7dpi_SAvOA <- DESeq(dds_1314_7dpi_SAvOA)
design(dds_1314_7dpi_SOvOA) <- formula(~ cultivar)
dds_1314_7dpi_SOvOA <- DESeq(dds_1314_7dpi_SOvOA)
design(dds_1314_7dpi_SAvSO) <- formula(~ cultivar)
dds_1314_7dpi_SAvSO <- DESeq(dds_1314_7dpi_SAvSO)
design(dds_1314_11dpi_SAvOA) <- formula(~ cultivar)
dds_1314_11dpi_SAvOA <- DESeq(dds_1314_11dpi_SAvOA)
design(dds_1314_11dpi_SOvOA) <- formula(~ cultivar)
dds_1314_11dpi_SOvOA <- DESeq(dds_1314_11dpi_SOvOA)
design(dds_1314_11dpi_SAvSO) <- formula(~ cultivar)
dds_1314_11dpi_SAvSO <- DESeq(dds_1314_11dpi_SAvSO)

##### check sizefactors ####
sink("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate.txt", append=TRUE, split=TRUE)
sizefactors(dds_F22_1dpi_SAvOA)
estimateSizeFactors(dds_F22_1dpi_SAvOA)
colSums(counts(dds_F22_1dpi_SAvOA))
colSums(counts(dds_F22_1dpi_SAvOA, normalized=T))
sizefactors(dds_F22_1dpi_SOvOA)
estimateSizeFactors(dds_F22_1dpi_SOvOA)
colSums(counts(dds_F22_1dpi_SOvOA))
colSums(counts(dds_F22_1dpi_SOvOA, normalized=T))
sizefactors(dds_F22_1dpi_SAvSO)
estimateSizeFactors(dds_F22_1dpi_SAvSO)
colSums(counts(dds_F22_1dpi_SAvSO))
colSums(counts(dds_F22_1dpi_SAvSO, normalized=T))
sizefactors(dds_F22_3dpi_SAvOA)
estimateSizeFactors(dds_F22_3dpi_SAvOA)
colSums(counts(dds_F22_3dpi_SAvOA))
colSums(counts(dds_F22_3dpi_SAvOA, normalized=T))
sizefactors(dds_F22_3dpi_SOvOA)
estimateSizeFactors(dds_F22_3dpi_SOvOA)
colSums(counts(dds_F22_3dpi_SOvOA))
colSums(counts(dds_F22_3dpi_SOvOA, normalized=T))
sizefactors(dds_F22_3dpi_SAvSO)
estimateSizeFactors(dds_F22_3dpi_SAvSO)
colSums(counts(dds_F22_3dpi_SAvSO))
colSums(counts(dds_F22_3dpi_SAvSO, normalized=T))
sizefactors(dds_F22_7dpi_SAvOA)
estimateSizeFactors(dds_F22_7dpi_SAvOA)
colSums(counts(dds_F22_7dpi_SAvOA))
colSums(counts(dds_F22_7dpi_SAvOA, normalized=T))
sizefactors(dds_F22_7dpi_SOvOA)
estimateSizeFactors(dds_F22_7dpi_SOvOA)
colSums(counts(dds_F22_7dpi_SOvOA))
colSums(counts(dds_F22_7dpi_SOvOA, normalized=T))
sizefactors(dds_F22_7dpi_SAvSO)
estimateSizeFactors(dds_F22_7dpi_SAvSO)
colSums(counts(dds_F22_7dpi_SAvSO))
colSums(counts(dds_F22_7dpi_SAvSO, normalized=T))
sizefactors(dds_F22_11dpi_SAvOA)
estimateSizeFactors(dds_F22_11dpi_SAvOA)
colSums(counts(dds_F22_11dpi_SAvOA))
colSums(counts(dds_F22_11dpi_SAvOA, normalized=T))
sizefactors(dds_F22_11dpi_SOvOA)
estimateSizeFactors(dds_F22_11dpi_SOvOA)
colSums(counts(dds_F22_11dpi_SOvOA))
colSums(counts(dds_F22_11dpi_SOvOA, normalized=T))
sizefactors(dds_F22_11dpi_SAvSO)
estimateSizeFactors(dds_F22_11dpi_SAvSO)
colSums(counts(dds_F22_11dpi_SAvSO))
colSums(counts(dds_F22_11dpi_SAvSO, normalized=T))

sizefactors(dds_1314_1dpi_SAvOA)
estimateSizeFactors(dds_1314_1dpi_SAvOA)
colSums(counts(dds_1314_1dpi_SAvOA))
colSums(counts(dds_1314_1dpi_SAvOA, normalized=T))
sizefactors(dds_1314_1dpi_SOvOA)
estimateSizeFactors(dds_1314_1dpi_SOvOA)
colSums(counts(dds_1314_1dpi_SOvOA))
colSums(counts(dds_1314_1dpi_SOvOA, normalized=T))
sizefactors(dds_1314_1dpi_SAvSO)
estimateSizeFactors(dds_1314_1dpi_SAvSO)
colSums(counts(dds_1314_1dpi_SAvSO))
colSums(counts(dds_1314_1dpi_SAvSO, normalized=T))
sizefactors(dds_1314_3dpi_SAvOA)
estimateSizeFactors(dds_1314_3dpi_SAvOA)
colSums(counts(dds_1314_3dpi_SAvOA))
colSums(counts(dds_1314_3dpi_SAvOA, normalized=T))
sizefactors(dds_1314_3dpi_SOvOA)
estimateSizeFactors(dds_1314_3dpi_SOvOA)
colSums(counts(dds_1314_3dpi_SOvOA))
colSums(counts(dds_1314_3dpi_SOvOA, normalized=T))
sizefactors(dds_1314_3dpi_SAvSO)
estimateSizeFactors(dds_1314_3dpi_SAvSO)
colSums(counts(dds_1314_3dpi_SAvSO))
colSums(counts(dds_1314_3dpi_SAvSO, normalized=T))
sizefactors(dds_1314_7dpi_SAvOA)
estimateSizeFactors(dds_1314_7dpi_SAvOA)
colSums(counts(dds_1314_7dpi_SAvOA))
colSums(counts(dds_1314_7dpi_SAvOA, normalized=T))
sizefactors(dds_1314_7dpi_SOvOA)
estimateSizeFactors(dds_1314_7dpi_SOvOA)
colSums(counts(dds_1314_7dpi_SOvOA))
colSums(counts(dds_1314_7dpi_SOvOA, normalized=T))
sizefactors(dds_1314_7dpi_SAvSO)
estimateSizeFactors(dds_1314_7dpi_SAvSO)
colSums(counts(dds_1314_7dpi_SAvSO))
colSums(counts(dds_1314_7dpi_SAvSO, normalized=T))
sizefactors(dds_1314_11dpi_SAvOA)
estimateSizeFactors(dds_1314_11dpi_SAvOA)
colSums(counts(dds_1314_11dpi_SAvOA))
colSums(counts(dds_1314_11dpi_SAvOA, normalized=T))
sizefactors(dds_1314_11dpi_SOvOA)
estimateSizeFactors(dds_1314_11dpi_SOvOA)
colSums(counts(dds_1314_11dpi_SOvOA))
colSums(counts(dds_1314_11dpi_SOvOA, normalized=T))
sizefactors(dds_1314_11dpi_SAvSO)
estimateSizeFactors(dds_1314_11dpi_SAvSO)
colSums(counts(dds_1314_11dpi_SAvSO))
colSums(counts(dds_1314_11dpi_SAvSO, normalized=T))
sink()
#### gene-wise dispersion estimations ####
pdf("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate_DispEst.pdf", height=11, width=8.5)
plotDispEsts(dds_F22_1dpi_SAvOA, main = "DispEst 1dpi F22_SAvOA")
plotDispEsts(dds_F22_1dpi_SOvOA, main = "DispEst 1dpi F22_SOvOA")
plotDispEsts(dds_F22_1dpi_SAvSO, main = "DispEst 1dpi F22_SAvSO")
plotDispEsts(dds_1314_1dpi_SAvOA, main = "DispEst 1dpi 1314_SAvOA")
plotDispEsts(dds_1314_1dpi_SOvOA, main = "DispEst 1dpi 1314_SOvOA")
plotDispEsts(dds_1314_1dpi_SAvSO, main = "DispEst 1dpi 1314_SAvSO")

plotDispEsts(dds_F22_3dpi_SAvOA, main = "DispEst 3dpi F22_SAvOA")
plotDispEsts(dds_F22_3dpi_SOvOA, main = "DispEst 3dpi F22_SOvOA")
plotDispEsts(dds_F22_3dpi_SAvSO, main = "DispEst 3dpi F22_SAvSO")
plotDispEsts(dds_1314_3dpi_SAvOA, main = "DispEst 3dpi 1314_SAvOA")
plotDispEsts(dds_1314_3dpi_SOvOA, main = "DispEst 3dpi 1314_SOvOA")
plotDispEsts(dds_1314_3dpi_SAvSO, main = "DispEst 3dpi 1314_SAvSO")

plotDispEsts(dds_F22_7dpi_SAvOA, main = "DispEst 7dpi F22_SAvOA")
plotDispEsts(dds_F22_7dpi_SOvOA, main = "DispEst 7dpi F22_SOvOA")
plotDispEsts(dds_F22_7dpi_SAvSO, main = "DispEst 7dpi F22_SAvSO")
plotDispEsts(dds_1314_7dpi_SAvOA, main = "DispEst 7dpi 1314_SAvOA")
plotDispEsts(dds_1314_7dpi_SOvOA, main = "DispEst 7dpi 1314_SOvOA")
plotDispEsts(dds_1314_7dpi_SAvSO, main = "DispEst 7dpi 1314_SAvSO")

plotDispEsts(dds_F22_11dpi_SAvOA, main = "DispEst 11dpi F22_SAvOA")
plotDispEsts(dds_F22_11dpi_SOvOA, main = "DispEst 11dpi F22_SOvOA")
plotDispEsts(dds_F22_11dpi_SAvSO, main = "DispEst 11dpi F22_SAvSO")
plotDispEsts(dds_1314_11dpi_SAvOA, main = "DispEst 11dpi 1314_SAvOA")
plotDispEsts(dds_1314_11dpi_SOvOA, main = "DispEst 11dpi 1314_SOvOA")
plotDispEsts(dds_1314_11dpi_SAvSO, main = "DispEst 11dpi 1314_SAvSO")
dev.off()

#### HYPOTHESIS TESTING - WALD TEST ####
# null hypothesis = no differential expression across the two sample groups (LFC == 0)
# For each dpi 1,3,7,11dpi for 1314 and F22:
# - pairwise comparisons:
# (1) SA vs OA
# (2) SO v OA
# (3) SA v SO

#### define contrasts ####
## What comparisons will be made
contrast_cultivar_SAvOA <- c("cultivar", "SA", "OA")
contrast_cultivar_SOvOA <- c("cultivar", "SO", "OA")
contrast_cultivar_SAvSO <- c("cultivar", "SA", "SO")

#### extract results table ####
res_table_F22_1dpi_SAvOA_unshrunken <- results(dds_F22_1dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_F22_1dpi_SOvOA_unshrunken <- results(dds_F22_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_F22_1dpi_SAvSO_unshrunken <- results(dds_F22_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)
res_table_1314_1dpi_SAvOA_unshrunken <- results(dds_1314_1dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_1314_1dpi_SOvOA_unshrunken <- results(dds_1314_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_1314_1dpi_SAvSO_unshrunken <- results(dds_1314_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)

res_table_F22_3dpi_SAvOA_unshrunken <- results(dds_F22_3dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_F22_3dpi_SOvOA_unshrunken <- results(dds_F22_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_F22_3dpi_SAvSO_unshrunken <- results(dds_F22_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)
res_table_1314_3dpi_SAvOA_unshrunken <- results(dds_1314_3dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_1314_3dpi_SOvOA_unshrunken <- results(dds_1314_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_1314_3dpi_SAvSO_unshrunken <- results(dds_1314_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)

res_table_F22_7dpi_SAvOA_unshrunken <- results(dds_F22_7dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_F22_7dpi_SOvOA_unshrunken <- results(dds_F22_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_F22_7dpi_SAvSO_unshrunken <- results(dds_F22_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)
res_table_1314_7dpi_SAvOA_unshrunken <- results(dds_1314_7dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_1314_7dpi_SOvOA_unshrunken <- results(dds_1314_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_1314_7dpi_SAvSO_unshrunken <- results(dds_1314_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)

res_table_F22_11dpi_SAvOA_unshrunken <- results(dds_F22_11dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_F22_11dpi_SOvOA_unshrunken <- results(dds_F22_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_F22_11dpi_SAvSO_unshrunken <- results(dds_F22_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)
res_table_1314_11dpi_SAvOA_unshrunken <- results(dds_1314_11dpi_SAvOA, contrasts=contrast_cultivar_SAvOA, alpha = 0.05)
res_table_1314_11dpi_SOvOA_unshrunken <- results(dds_1314_3dpi_SOvOA, contrasts=contrast_cultivar_SOvOA, alpha = 0.05)
res_table_1314_11dpi_SAvSO_unshrunken <- results(dds_1314_3dpi_SAvSO, contrasts=contrast_cultivar_SAvSO, alpha = 0.05)

#### and shrink the log2 fold changes ####
res_table_F22_1dpi_SAvOA_shrunk <- lfcShrink(dds_F22_1dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_F22_1dpi_SAvOA_unshrunken)
res_table_F22_1dpi_SOvOA_shrunk <- lfcShrink(dds_F22_1dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_F22_1dpi_SOvOA_unshrunken)
res_table_F22_1dpi_SAvSO_shrunk <- lfcShrink(dds_F22_1dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_F22_1dpi_SAvSO_unshrunken)
res_table_1314_1dpi_SAvOA_shrunk <- lfcShrink(dds_1314_1dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_1314_1dpi_SAvOA_unshrunken)
res_table_1314_1dpi_SOvOA_shrunk <- lfcShrink(dds_1314_1dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_1314_1dpi_SOvOA_unshrunken)
res_table_1314_1dpi_SAvSO_shrunk <- lfcShrink(dds_1314_1dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_1314_1dpi_SAvSO_unshrunken)

res_table_F22_3dpi_SAvOA_shrunk <- lfcShrink(dds_F22_3dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_F22_3dpi_SAvOA_unshrunken)
res_table_F22_3dpi_SOvOA_shrunk <- lfcShrink(dds_F22_3dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_F22_3dpi_SOvOA_unshrunken)
res_table_F22_3dpi_SAvSO_shrunk <- lfcShrink(dds_F22_3dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_F22_3dpi_SAvSO_unshrunken)
res_table_1314_3dpi_SAvOA_shrunk <- lfcShrink(dds_1314_3dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_1314_3dpi_SAvOA_unshrunken)
res_table_1314_3dpi_SOvOA_shrunk <- lfcShrink(dds_1314_3dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_1314_3dpi_SOvOA_unshrunken)
res_table_1314_3dpi_SAvSO_shrunk <- lfcShrink(dds_1314_3dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_1314_3dpi_SAvSO_unshrunken)

res_table_F22_7dpi_SAvOA_shrunk <- lfcShrink(dds_F22_7dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_F22_7dpi_SAvOA_unshrunken)
res_table_F22_7dpi_SOvOA_shrunk <- lfcShrink(dds_F22_7dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_F22_7dpi_SOvOA_unshrunken)
res_table_F22_7dpi_SAvSO_shrunk <- lfcShrink(dds_F22_7dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_F22_7dpi_SAvSO_unshrunken)
res_table_1314_7dpi_SAvOA_shrunk <- lfcShrink(dds_1314_7dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_1314_7dpi_SAvOA_unshrunken)
res_table_1314_7dpi_SOvOA_shrunk <- lfcShrink(dds_1314_7dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_1314_7dpi_SOvOA_unshrunken)
res_table_1314_7dpi_SAvSO_shrunk <- lfcShrink(dds_1314_7dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_1314_7dpi_SAvSO_unshrunken)

res_table_F22_11dpi_SAvOA_shrunk <- lfcShrink(dds_F22_11dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_F22_11dpi_SAvOA_unshrunken)
res_table_F22_11dpi_SOvOA_shrunk <- lfcShrink(dds_F22_11dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_F22_11dpi_SOvOA_unshrunken)
res_table_F22_11dpi_SAvSO_shrunk <- lfcShrink(dds_F22_11dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_F22_11dpi_SAvSO_unshrunken)
res_table_1314_11dpi_SAvOA_shrunk <- lfcShrink(dds_1314_11dpi_SAvOA, contrast=contrast_cultivar_SAvOA, res=res_table_1314_11dpi_SAvOA_unshrunken)
res_table_1314_11dpi_SOvOA_shrunk <- lfcShrink(dds_1314_11dpi_SOvOA, contrast=contrast_cultivar_SOvOA, res=res_table_1314_11dpi_SOvOA_unshrunken)
res_table_1314_11dpi_SAvSO_shrunk <- lfcShrink(dds_1314_11dpi_SAvSO, contrast=contrast_cultivar_SAvSO, res=res_table_1314_11dpi_SAvSO_unshrunken)

#### results as MA plots - see sigDEGs across range levels ####
pdf("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate_MAplots.pdf", height=11, width=8.5)
plotMA_res_table_F22_1dpi_SAvOA_unshrunken <- plotMA(res_table_F22_1dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 1dpi F22 SAvOA unshrunken")
plotMA_res_table_F22_1dpi_SAvOA_shrunk <- plotMA(res_table_F22_1dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 1dpi SAvOA")
plotMA_res_table_F22_1dpi_SOvOA_unshrunken <- plotMA(res_table_F22_1dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 1dpi F22 SOvOA unshrunken")
plotMA_res_table_F22_1dpi_SOvOA_shrunk <- plotMA(res_table_F22_1dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 1dpi F22 SOvOA")
plotMA_res_table_F22_1dpi_SAvSO_unshrunken <- plotMA(res_table_F22_1dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 1dpi F22 SAvSO unshrunken")
plotMA_res_table_F22_1dpi_SAvSO_shrunk <- plotMA(res_table_F22_1dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 1dpi F22 SAvSO")
plotMA_res_table_1314_1dpi_SAvOA_unshrunken <- plotMA(res_table_1314_1dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 1dpi 1314 SAvOA unshrunken")
plotMA_res_table_1314_1dpi_SAvOA_shrunk <- plotMA(res_table_1314_1dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 1dpi SAvOA")
plotMA_res_table_1314_1dpi_SOvOA_unshrunken <- plotMA(res_table_1314_1dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 1dpi 1314 SOvOA unshrunken")
plotMA_res_table_1314_1dpi_SOvOA_shrunk <- plotMA(res_table_1314_1dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 1dpi 1314 SOvOA")
plotMA_res_table_1314_1dpi_SAvSO_unshrunken <- plotMA(res_table_1314_1dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 1dpi 1314 SAvSO unshrunken")
plotMA_res_table_1314_1dpi_SAvSO_shrunk <- plotMA(res_table_1314_1dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 1dpi 1314 SAvSO")

plotMA_res_table_F22_3dpi_SAvOA_unshrunken <- plotMA(res_table_F22_3dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 3dpi F22 SAvOA unshrunken")
plotMA_res_table_F22_3dpi_SAvOA_shrunk <- plotMA(res_table_F22_3dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 3dpi SAvOA")
plotMA_res_table_F22_3dpi_SOvOA_unshrunken <- plotMA(res_table_F22_3dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 3dpi F22 SOvOA unshrunken")
plotMA_res_table_F22_3dpi_SOvOA_shrunk <- plotMA(res_table_F22_3dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 3dpi F22 SOvOA")
plotMA_res_table_F22_3dpi_SAvSO_unshrunken <- plotMA(res_table_F22_3dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 3dpi F22 SAvSO unshrunken")
plotMA_res_table_F22_3dpi_SAvSO_shrunk <- plotMA(res_table_F22_3dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 3dpi F22 SAvSO")
plotMA_res_table_1314_3dpi_SAvOA_unshrunken <- plotMA(res_table_1314_3dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 3dpi 1314 SAvOA unshrunken")
plotMA_res_table_1314_3dpi_SAvOA_shrunk <- plotMA(res_table_1314_3dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 3dpi SAvOA")
plotMA_res_table_1314_3dpi_SOvOA_unshrunken <- plotMA(res_table_1314_3dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 3dpi 1314 SOvOA unshrunken")
plotMA_res_table_1314_3dpi_SOvOA_shrunk <- plotMA(res_table_1314_3dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 3dpi 1314 SOvOA")
plotMA_res_table_1314_3dpi_SAvSO_unshrunken <- plotMA(res_table_1314_3dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 3dpi 1314 SAvSO unshrunken")
plotMA_res_table_1314_3dpi_SAvSO_shrunk <- plotMA(res_table_1314_3dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 3dpi 1314 SAvSO")

plotMA_res_table_F22_7dpi_SAvOA_unshrunken <- plotMA(res_table_F22_7dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 7dpi F22 SAvOA unshrunken")
plotMA_res_table_F22_7dpi_SAvOA_shrunk <- plotMA(res_table_F22_7dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 7dpi SAvOA")
plotMA_res_table_F22_7dpi_SOvOA_unshrunken <- plotMA(res_table_F22_7dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 7dpi F22 SOvOA unshrunken")
plotMA_res_table_F22_7dpi_SOvOA_shrunk <- plotMA(res_table_F22_7dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 7dpi F22 SOvOA")
plotMA_res_table_F22_7dpi_SAvSO_unshrunken <- plotMA(res_table_F22_7dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 7dpi F22 SAvSO unshrunken")
plotMA_res_table_F22_7dpi_SAvSO_shrunk <- plotMA(res_table_F22_7dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 7dpi F22 SAvSO")
plotMA_res_table_1314_7dpi_SAvOA_unshrunken <- plotMA(res_table_1314_7dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 7dpi 1314 SAvOA unshrunken")
plotMA_res_table_1314_7dpi_SAvOA_shrunk <- plotMA(res_table_1314_7dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 7dpi SAvOA")
plotMA_res_table_1314_7dpi_SOvOA_unshrunken <- plotMA(res_table_1314_7dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 7dpi 1314 SOvOA unshrunken")
plotMA_res_table_1314_7dpi_SOvOA_shrunk <- plotMA(res_table_1314_7dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 7dpi 1314 SOvOA")
plotMA_res_table_1314_7dpi_SAvSO_unshrunken <- plotMA(res_table_1314_7dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 7dpi 1314 SAvSO unshrunken")
plotMA_res_table_1314_7dpi_SAvSO_shrunk <- plotMA(res_table_1314_7dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 7dpi 1314 SAvSO")

plotMA_res_table_F22_11dpi_SAvOA_unshrunken <- plotMA(res_table_F22_11dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 11dpi F22 SAvOA unshrunken")
plotMA_res_table_F22_11dpi_SAvOA_shrunk <- plotMA(res_table_F22_11dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 11dpi SAvOA")
plotMA_res_table_F22_11dpi_SOvOA_unshrunken <- plotMA(res_table_F22_11dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 11dpi F22 SOvOA unshrunken")
plotMA_res_table_F22_11dpi_SOvOA_shrunk <- plotMA(res_table_F22_11dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 11dpi F22 SOvOA")
plotMA_res_table_F22_11dpi_SAvSO_unshrunken <- plotMA(res_table_F22_11dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 11dpi F22 SAvSO unshrunken")
plotMA_res_table_F22_11dpi_SAvSO_shrunk <- plotMA(res_table_F22_11dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 11dpi F22 SAvSO")
plotMA_res_table_1314_11dpi_SAvOA_unshrunken <- plotMA(res_table_1314_11dpi_SAvOA_unshrunken, ylim=c(-10,10), main="MAplot 11dpi 1314 SAvOA unshrunken")
plotMA_res_table_1314_11dpi_SAvOA_shrunk <- plotMA(res_table_1314_11dpi_SAvOA_shrunk, ylim=c(-10,10), main="MAplot 11dpi SAvOA")
plotMA_res_table_1314_11dpi_SOvOA_unshrunken <- plotMA(res_table_1314_11dpi_SOvOA_unshrunken, ylim=c(-10,10), main="MAplot 11dpi 1314 SOvOA unshrunken")
plotMA_res_table_1314_11dpi_SOvOA_shrunk <- plotMA(res_table_1314_11dpi_SOvOA_shrunk, ylim=c(-10,10), main="MAplot 11dpi 1314 SOvOA")
plotMA_res_table_1314_11dpi_SAvSO_unshrunken <- plotMA(res_table_1314_11dpi_SAvSO_unshrunken, ylim=c(-10,10), main="MAplot 11dpi 1314 SAvSO unshrunken")
plotMA_res_table_1314_11dpi_SAvSO_shrunk <- plotMA(res_table_1314_11dpi_SAvSO_shrunk, ylim=c(-10,10), main="MAplot 11dpi 1314 SAvSO")
dev.off()

#### EXPLORE RESULTS ####
#multiple testing problem: more genes tested, more false positive rate
# - DESeq2 removes unlikely genes with low count numbers and outlier samples (gene-levelQC)
# - correct for multiple testing to reduce false positives using Benjamini-Hochberg method
# ALWAYS USE p-adj method, uses FDR<0.05
sink("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate_results.txt", append=TRUE, split=TRUE)
class(res_table_F22_1dpi_SAvOA_shrunk)
class(res_table_F22_1dpi_SOvOA_shrunk)
class(res_table_F22_1dpi_SAvSO_shrunk)
class(res_table_1314_1dpi_SAvOA_shrunk)
class(res_table_1314_1dpi_SOvOA_shrunk)
class(res_table_1314_1dpi_SAvSO_shrunk)
class(res_table_F22_3dpi_SAvOA_shrunk)
class(res_table_F22_3dpi_SOvOA_shrunk)
class(res_table_F22_3dpi_SAvSO_shrunk)
class(res_table_1314_3dpi_SAvOA_shrunk)
class(res_table_1314_3dpi_SOvOA_shrunk)
class(res_table_1314_3dpi_SAvSO_shrunk)
class(res_table_F22_7dpi_SAvOA_shrunk)
class(res_table_F22_7dpi_SOvOA_shrunk)
class(res_table_F22_7dpi_SAvSO_shrunk)
class(res_table_1314_7dpi_SAvOA_shrunk)
class(res_table_1314_7dpi_SOvOA_shrunk)
class(res_table_1314_7dpi_SAvSO_shrunk)
class(res_table_F22_11dpi_SAvOA_shrunk)
class(res_table_F22_11dpi_SOvOA_shrunk)
class(res_table_F22_11dpi_SAvSO_shrunk)
class(res_table_1314_11dpi_SAvOA_shrunk)
class(res_table_1314_11dpi_SOvOA_shrunk)
class(res_table_1314_11dpi_SAvSO_shrunk)
#check comparison (thus LFC) as expected i.e. CON~reference
mcols(res_table_F22_1dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_F22_1dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_F22_1dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_1314_1dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_1314_1dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_1314_1dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_F22_3dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_F22_3dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_F22_3dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_1314_3dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_1314_3dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_1314_3dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_F22_7dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_F22_7dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_F22_7dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_1314_7dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_1314_7dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_1314_7dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_F22_11dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_F22_11dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_F22_11dpi_SAvSO_shrunk, use.names=T)
mcols(res_table_1314_11dpi_SAvOA_shrunk, use.names=T)
mcols(res_table_1314_11dpi_SOvOA_shrunk, use.names=T)
mcols(res_table_1314_11dpi_SAvSO_shrunk, use.names=T)
# check column names
colnames(res_table_F22_1dpi_SAvOA_shrunk)
colnames(res_table_F22_1dpi_SOvOA_shrunk)
colnames(res_table_F22_1dpi_SAvSO_shrunk)
colnames(res_table_1314_1dpi_SAvOA_shrunk)
colnames(res_table_1314_1dpi_SOvOA_shrunk)
colnames(res_table_1314_1dpi_SAvSO_shrunk)
colnames(res_table_F22_3dpi_SAvOA_shrunk)
colnames(res_table_F22_3dpi_SOvOA_shrunk)
colnames(res_table_F22_3dpi_SAvSO_shrunk)
colnames(res_table_1314_3dpi_SAvOA_shrunk)
colnames(res_table_1314_3dpi_SOvOA_shrunk)
colnames(res_table_1314_3dpi_SAvSO_shrunk)
colnames(res_table_F22_7dpi_SAvOA_shrunk)
colnames(res_table_F22_7dpi_SOvOA_shrunk)
colnames(res_table_F22_7dpi_SAvSO_shrunk)
colnames(res_table_1314_7dpi_SAvOA_shrunk)
colnames(res_table_1314_7dpi_SOvOA_shrunk)
colnames(res_table_1314_7dpi_SAvSO_shrunk)
colnames(res_table_F22_11dpi_SAvOA_shrunk)
colnames(res_table_F22_11dpi_SOvOA_shrunk)
colnames(res_table_F22_11dpi_SAvSO_shrunk)
colnames(res_table_1314_11dpi_SAvOA_shrunk)
colnames(res_table_1314_11dpi_SOvOA_shrunk)
colnames(res_table_1314_11dpi_SAvSO_shrunk)
sink()

##### SUMMARISE RESULTS ####
#### tells whats up/down-regulated and number genes with non-zero total read count and number genes not included ####
sink("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate_summary.txt", append=TRUE, split=TRUE)
summary(res_table_F22_1dpi_SAvOA_shrunk)
summary(res_table_F22_1dpi_SOvOA_shrunk)
summary(res_table_F22_1dpi_SAvSO_shrunk)
summary(res_table_1314_1dpi_SAvOA_shrunk)
summary(res_table_1314_1dpi_SOvOA_shrunk)
summary(res_table_1314_1dpi_SAvSO_shrunk)
summary(res_table_F22_3dpi_SAvOA_shrunk)
summary(res_table_F22_3dpi_SOvOA_shrunk)
summary(res_table_F22_3dpi_SAvSO_shrunk)
summary(res_table_1314_3dpi_SAvOA_shrunk)
summary(res_table_1314_3dpi_SOvOA_shrunk)
summary(res_table_1314_3dpi_SAvSO_shrunk)
summary(res_table_F22_7dpi_SAvOA_shrunk)
summary(res_table_F22_7dpi_SOvOA_shrunk)
summary(res_table_F22_7dpi_SAvSO_shrunk)
summary(res_table_1314_7dpi_SAvOA_shrunk)
summary(res_table_1314_7dpi_SOvOA_shrunk)
summary(res_table_1314_7dpi_SAvSO_shrunk)
summary(res_table_F22_11dpi_SAvOA_shrunk)
summary(res_table_F22_11dpi_SOvOA_shrunk)
summary(res_table_F22_11dpi_SAvSO_shrunk)
summary(res_table_1314_11dpi_SAvOA_shrunk)
summary(res_table_1314_11dpi_SOvOA_shrunk)
summary(res_table_1314_11dpi_SAvSO_shrunk)
sink()
#### subset table to include only those that are significant ####
## set thresholds
padj.cutoff <- 0.05
# subset table to include only those that are significant
library(tibble)
library("dplyr")

sig_F22_1dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_1dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_1dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_1dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_1dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_1dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_1dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_1dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_1dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_1dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_1dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_1dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_3dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_3dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_3dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_3dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_3dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_3dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_3dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_3dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_3dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_3dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_3dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_3dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_7dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_7dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_7dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_7dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_7dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_7dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_7dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_7dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_7dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_7dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_7dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_7dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_11dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_11dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_11dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_11dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_F22_11dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_F22_11dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_11dpi_SAvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_11dpi_SAvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_11dpi_SOvOA_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_11dpi_SOvOA_shrunk), var="gene")), padj < padj.cutoff)
sig_1314_11dpi_SAvSO_shrunk <- filter(as_tibble(rownames_to_column(data.frame(res_table_1314_11dpi_SAvSO_shrunk), var="gene")), padj < padj.cutoff)

sink("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_CON_summary.txt", append=TRUE, split=TRUE)
length(pull(sig_F22_1dpi_SAvOA_shrunk, gene))
length(pull(sig_F22_1dpi_SOvOA_shrunk, gene))
length(pull(sig_F22_1dpi_SAvSO_shrunk, gene))
length(pull(sig_1314_1dpi_SAvOA_shrunk, gene))
length(pull(sig_1314_1dpi_SOvOA_shrunk, gene))
length(pull(sig_1314_1dpi_SAvSO_shrunk, gene))
length(pull(sig_F22_3dpi_SAvOA_shrunk, gene))
length(pull(sig_F22_3dpi_SOvOA_shrunk, gene))
length(pull(sig_F22_3dpi_SAvSO_shrunk, gene))
length(pull(sig_1314_3dpi_SAvOA_shrunk, gene))
length(pull(sig_1314_3dpi_SOvOA_shrunk, gene))
length(pull(sig_1314_3dpi_SAvSO_shrunk, gene))
length(pull(sig_F22_7dpi_SAvOA_shrunk, gene))
length(pull(sig_F22_7dpi_SOvOA_shrunk, gene))
length(pull(sig_F22_7dpi_SAvSO_shrunk, gene))
length(pull(sig_1314_7dpi_SAvOA_shrunk, gene))
length(pull(sig_1314_7dpi_SOvOA_shrunk, gene))
length(pull(sig_1314_7dpi_SAvSO_shrunk, gene))
length(pull(sig_F22_11dpi_SAvOA_shrunk, gene))
length(pull(sig_F22_11dpi_SOvOA_shrunk, gene))
length(pull(sig_F22_11dpi_SAvSO_shrunk, gene))
length(pull(sig_1314_11dpi_SAvOA_shrunk, gene))
length(pull(sig_1314_11dpi_SOvOA_shrunk, gene))
length(pull(sig_1314_11dpi_SAvSO_shrunk, gene))
sink()

write.table(sig_F22_1dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_1dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_1dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_1dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_1dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_1dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_1dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_1dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_1dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_1dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_1dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_1dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_3dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_3dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_3dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_3dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_3dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_3dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_3dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_3dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_3dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_3dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_3dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_3dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_7dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_7dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_7dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_7dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_7dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_7dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_7dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_7dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_7dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_7dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_7dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_7dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_11dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_11dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_11dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_11dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_F22_11dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_F22_11dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_11dpi_SAvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_11dpi_SAvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_11dpi_SOvOA_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_11dpi_SOvOA_shrunk.txt", quote=F, col.names=NA)
write.table(sig_1314_11dpi_SAvSO_shrunk, file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/sig_1314_11dpi_SAvSO_shrunk.txt", quote=F, col.names=NA)

pdf("/Users/rbadgami/Desktop/data2/Results_figures/DESeq2_isolate_hists.pdf", height=11, width=8.5)
hist(res_table_F22_1dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_1dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_1dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_1dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_1dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_1dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_3dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_3dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_3dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_3dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_3dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_3dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_7dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_7dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_7dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_7dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_7dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_7dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_11dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_11dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_F22_11dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_11dpi_SAvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_11dpi_SOvOA_shrunk$padj, breaks=40, col="grey")
hist(res_table_1314_11dpi_SAvSO_shrunk$padj, breaks=40, col="grey")
dev.off()

#### SUC/RES up/donwreg
write.table(filter(sig_F22_1dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_1dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_1dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_1dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_1dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_1dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_1dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_1dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_1dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_3dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_3dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_3dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_3dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_7dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_7dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_7dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_7dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_F22_11dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_F22_11dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SAvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SAvOA_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SAvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SAvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SOvOA_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SOvOA_RES_SOupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SOvOA_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SOvOA_SUS_OAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SAvSO_shrunk, log2FoldChange > 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SAvSO_RES_SAupreg.txt", quote=F, col.names=NA)
write.table(filter(sig_1314_11dpi_SAvSO_shrunk, log2FoldChange < 0), file="/Users/rbadgami/Desktop/data2/read_count_data/DESeq2_isolate/LFC_1314_11dpi_SAvSO_SUS_SOupreg.txt", quote=F, col.names=NA)

length(pull(sig_F22_1dpi_SOvOA_shrunk, gene))-length(pull(filter(sig_F22_1dpi_SOvOA_shrunk, log2FoldChange > 1.00), gene)) - length(pull(filter(sig_F22_1dpi_SOvOA_shrunk, log2FoldChange <1.00), gene))


length(pull(filter(sig_F22_1dpi_SOvOA_shrunk, log2FoldChange == 0), gene))


View(sig_F22_1dpi_SAvOA_shrunk)
